### ISSUE TITLE
DENV Colombia Phylogeography

### ISSUE THREAD

**Issue by camposaca** [drexler-virus-epidemiology/group-documentation#18]
We have genomes of DENV-1, DENV-2 and DENV-4 from Colombia and I need to analyze how many and from where were the entries.

Could you please provide to me a dataset with Latin America sequences for each DENV serotype?

I have also a small fragment of DENV-3 (only 250nt from PanFlavi assay) and I would like to run one bayesian analysis only to confirm DENV-3 and maybe genotype. I runned in genome detective website and the fragment back as DENV-3 genotype III

https://www.genomedetective.com/app/typingtool/dengue/job/6eac327b-6284-42a5-aa91-8b1c3ae5b314/sequence-0

**Comment by Dokandres** [comment]
Done.
